Importing The Libraries:

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

# checking the version of tensorflow
tf.__version__

'2.18.0'

Importing The DataSet:

In [4]:
dataset = pd.read_excel("Folds5x2_pp.xlsx")

# checking the dataset
print(dataset.head())
print(dataset.info())

      AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB
None


Splitting The Dataset

In [5]:
# X is input features
# y is dependent variable

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X.shape)
print(y.shape)

(9568, 4)
(9568,)


Splitting the data into Train and Test

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(7654, 4) (7654,)
(1914, 4) (1914,)


ANN Architecture

Input -> 6 neurons -> 6 neurons -> Output

In [11]:
ann = tf.keras.models.Sequential([
    tf.keras.layers.Dense(6, activation='relu', name='input_hidden1'),
    tf.keras.layers.Dense(6, activation='relu', name='hidden1_hidden2'),
    tf.keras.layers.Dense(1, name='hidden2_output') # use sigmoid or softmax as actication for last layer, but we are doing regression so use NONE(default) activation
])
ann.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_hidden1 (Dense)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden1_hidden2 (Dense)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hidden2_output (Dense)          │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Compiling and Training of ANN

In [12]:
ann.compile(optimizer='adam', loss='mean_squared_error')
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 427.6540
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 66.0199
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 61.4793
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 55.4199
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51.2257
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 46.2694
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 43.5386
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 40.2656
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 37.0507
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 34.9125
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 34.1640
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 34.5501
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 31.5029
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 31.7905
Epoch 15/100
240/240 ━━━━━━━

Save the Model

In [15]:
tf.keras.models.save_model(ann, 'powerplant_ann.keras')

Testing


In [21]:
y_pred = ann.predict(X_test)
y_pred.shape

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  


(1914, 1)

In [33]:
y_test = y_test.reshape(len(y_test), 1)
y_pred = y_pred.reshape(len(y_pred), 1)
difference = np.abs(y_pred - y_test)
results = np.concatenate((y_pred, y_test, difference), axis=1)

In [38]:
print(results)

[[456.77 455.27   1.5 ]
 [438.92 436.31   2.61]
 [433.77 440.68   6.91]
 ...
 [481.32 479.53   1.79]
 [435.89 435.76   0.13]
 [460.05 457.1    2.95]]
